spring.application.name=ParkingManagement
server.port=8081
#MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/parking_db
spring.datasource.username= root
spring.datasource.password=Harshita@2002

# JPA & Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# KAFKA CONFIGURATION

# 1. Connection
spring.kafka.bootstrap-servers=localhost:29092

# 2. Consumer (The Listener)
spring.kafka.consumer.group-id=parking-system-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 3. Producer (The Sender)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# 4. Automatic Retries (Handle Failures)
# If a message fails, wait 1 second, then try again. Max 3 attempts.
spring.kafka.consumer.properties.spring.json.trusted.packages=*